import type { CategorySection } from '@/_types/filters';

// count = number of matching recipes in the current dataset.
// Items with count === 0 are hidden in the UI but kept here so they appear
// automatically once recipes are added (run sortCategoryItems in components).

export const CATEGORY_SECTIONS: CategorySection[] = [
  {
    hero: true,
    id: 'pick_your_pace',
    items: [
      {
        count: 1,
        description: 'Quick, easy mains ready in under 30 minutes.',
        filters: {
          difficulty: 'easy',
          meal_type: 'main',
          time_category: 'quick',
        },
        id: 'weeknight-winners',
        image: '/images/recipes/cashew-chicken.webp',
        label: 'Weeknight Winners',
        order: 1,
      },
      {
        count: 8,
        description: 'Dishes that reward a bit more time in the kitchen.',
        filters: { difficulty: 'moderate', time_category: ['medium', 'long'] },
        id: 'worth-the-effort',
        image: '/images/recipes/lamb-tagine.jpg',
        label: 'Worth the Effort',
        order: 2,
      },
      {
        count: 1,
        description: 'Ambitious recipes for when you have the whole afternoon.',
        filters: { difficulty: 'challenging', time_category: 'long' },
        id: 'weekend-project',
        image: '/images/recipes/steak-rarebit.webp',
        label: 'Weekend Project',
        order: 3,
      },
    ],
    order: 1,
    showInMenu: true,
    title: 'Pick Your Pace',
  },
  {
    id: 'dish_style',
    items: [
      {
        count: 0,
        description:
          'Fragrant, spiced curries from mild and creamy to fiery and bold.',
        filters: { dish_style: 'curry' },
        id: 'curry',
        image: '',
        label: 'Curry',
      },
      {
        count: 0,
        description:
          'Silky, springy noodles in broths, sauces, and stir-fries.',
        filters: { dish_style: 'noodles' },
        id: 'noodles',
        image: '',
        label: 'Noodles',
      },
      {
        count: 3,
        description:
          'Classic and comforting — from quick weeknight pasta to slow-cooked sauces.',
        filters: { dish_style: 'pasta' },
        id: 'pasta',
        image: '/images/recipes/creamy-prawn-tagliatelle.webp',
        label: 'Pasta',
      },
      {
        count: 1,
        description: 'Hearty topped and pastry-wrapped favourites.',
        filters: { dish_style: 'pie' },
        id: 'pie',
        image: '/images/recipes/curried-lentil-cottage-pie.webp',
        label: 'Pie',
      },
      {
        count: 0,
        description:
          'Homemade pizza — thin, crispy, and loaded with good things.',
        filters: { dish_style: 'pizza' },
        id: 'pizza',
        image: '',
        label: 'Pizza',
      },
      {
        count: 1,
        description:
          'From fragrant pilau to sticky rice — dishes where rice takes centre stage.',
        filters: { dish_style: 'rice-dish' },
        id: 'rice-dish',
        image: '/images/recipes/pilau-rice.webp',
        label: 'Rice Dish',
      },
      {
        count: 0,
        description:
          'Showstopping roasts for a leisurely Sunday or a special occasion.',
        filters: { dish_style: 'roast' },
        id: 'roast',
        image: '',
        label: 'Roast',
      },
      {
        count: 0,
        description:
          'Fresh, vibrant salads that work as a side or a meal in themselves.',
        filters: { dish_style: 'salad' },
        id: 'salad',
        image: '',
        label: 'Salad',
      },
      {
        count: 0,
        description: 'Warming, restorative soups for any season.',
        filters: { dish_style: 'soup' },
        id: 'soup',
        image: '',
        label: 'Soup',
      },
      {
        count: 2,
        description: 'Slow-cooked, deeply flavoured one-pot dishes.',
        filters: { dish_style: 'stew-casserole' },
        id: 'stew-and-casserole',
        image: '/images/recipes/lamb-tagine.jpg',
        label: 'Stew & Casserole',
      },
      {
        count: 0,
        description: 'High heat, fast cooking — bold flavours in minutes.',
        filters: { dish_style: 'stir-fry' },
        id: 'stir-fry',
        image: '',
        label: 'Stir Fry',
      },
    ],
    order: 2,
    showInMenu: true,
    title: 'In the Mood For',
  },
  {
    id: 'cooking_method',
    items: [
      {
        count: 0,
        description:
          'Set it and forget it — long, slow cooking with minimal effort.',
        filters: { cooking_method: 'slow-cooker' },
        id: 'slow-cooker',
        image: '',
        label: 'Slow Cooker',
      },
      {
        count: 0,
        description: 'Everything on one tray — easy prep, easy clean-up.',
        filters: { cooking_method: 'traybake' },
        id: 'traybake',
        image: '',
        label: 'Traybake',
      },
      {
        count: 2,
        description:
          'Fewer dishes, more flavour — everything cooked in a single pot or pan.',
        filters: { cooking_method: 'one-pot' },
        id: 'one-pot',
        image: '/images/recipes/lamb-tagine.jpg',
        label: 'One Pot',
      },
      {
        count: 1,
        description: 'Crispy results with less oil and less time.',
        filters: { cooking_method: 'air-fryer' },
        id: 'air-fryer',
        image: '/images/recipes/air-fryer-crispy-chilli-beef.webp',
        label: 'Air Fryer',
      },
      {
        count: 0,
        description: 'Slow-cooker results in a fraction of the time.',
        filters: { cooking_method: 'pressure-cooker' },
        id: 'pressure-cooker',
        image: '',
        label: 'Pressure Cooker',
      },
      {
        count: 0,
        description: 'Charred edges and smoky flavour — inside or out.',
        filters: { cooking_method: 'grill' },
        id: 'grill',
        image: '',
        label: 'Grill',
      },
      {
        count: 0,
        description: "Low and slow for deep, smoky flavour you can't rush.",
        filters: { cooking_method: 'smoker' },
        id: 'smoker',
        image: '',
        label: 'Smoker',
      },
    ],
    order: 3,
    showInMenu: true,
    title: 'How Do You Want to Cook It?',
  },
  {
    id: 'meal_type',
    items: [
      {
        count: 0,
        description:
          'Small bites to start — light, shareable, and full of flavour.',
        filters: { meal_type: 'appetiser' },
        id: 'appetiser',
        image: '',
        label: 'Appetiser',
      },
      {
        count: 1,
        description: 'Morning recipes worth getting up for.',
        filters: { meal_type: 'breakfast' },
        id: 'breakfast',
        image: '/images/recipes/ham-and-cheese-galettes.webp',
        label: 'Breakfast',
      },
      {
        count: 0,
        description:
          'Sauces, dressings, and preserves to elevate everything else.',
        filters: { meal_type: 'condiment' },
        id: 'condiment',
        image: '',
        label: 'Condiment',
      },
      {
        count: 0,
        description:
          'Cocktails, mocktails, and drinks worth making from scratch.',
        filters: { meal_type: 'drink' },
        id: 'drink',
        image: '',
        label: 'Drink',
      },
      {
        count: 11,
        description:
          'The centrepiece — satisfying mains for any night of the week.',
        filters: { meal_type: 'main' },
        id: 'main',
        image: '/images/recipes/lamb-tagine.jpg',
        label: 'Main',
      },
      {
        count: 1,
        description: 'Indulgent desserts and sweet finishes.',
        filters: { meal_type: 'pudding' },
        id: 'pudding',
        image: '/images/recipes/sticky-date-and-banana-pudding.webp',
        label: 'Pudding',
      },
      {
        count: 2,
        description: 'The dishes that make the meal.',
        filters: { meal_type: 'side' },
        id: 'side',
        image: '/images/recipes/gunpowder-potatoes.webp',
        label: 'Side',
      },
      {
        count: 0,
        description:
          'Something to keep you going — quick, easy, and satisfying.',
        filters: { meal_type: 'snack' },
        id: 'snack',
        image: '',
        label: 'Snack',
      },
    ],
    order: 4,
    showInMenu: true,
    title: 'By Meal Type',
  },
  {
    id: 'cuisine',
    items: [
      {
        count: 0,
        description: 'Bold, comforting classics from across the States.',
        filters: { cuisine: 'american' },
        id: 'american',
        image: '',
        label: 'American',
      },
      {
        count: 4,
        description: 'Hearty classics and modern takes on British favourites.',
        filters: { cuisine: 'british' },
        id: 'british',
        image: '/images/recipes/steak-rarebit.webp',
        label: 'British',
      },
      {
        count: 1,
        description: 'Bold, balanced flavours from Chinese cooking.',
        filters: { cuisine: 'chinese' },
        id: 'chinese',
        image: '/images/recipes/cashew-chicken.webp',
        label: 'Chinese',
      },
      {
        count: 1,
        description: 'Elegant techniques and classic French flavours.',
        filters: { cuisine: 'french' },
        id: 'french',
        image: '/images/recipes/ham-and-cheese-galettes.webp',
        label: 'French',
      },
      {
        count: 0,
        description:
          'Sun-drenched flavours — olive oil, lemon, herbs, and the sea.',
        filters: { cuisine: 'greek' },
        id: 'greek',
        image: '',
        label: 'Greek',
      },
      {
        count: 4,
        description:
          'Aromatic spices and vibrant flavours from the Indian subcontinent.',
        filters: { cuisine: 'indian' },
        id: 'indian',
        image: '/images/recipes/chicken-berry-britannia.webp',
        label: 'Indian',
      },
      {
        count: 3,
        description:
          'Sun-soaked simplicity — pasta, risotto, and Italian classics.',
        filters: { cuisine: 'italian' },
        id: 'italian',
        image: '/images/recipes/creamy-prawn-tagliatelle.webp',
        label: 'Italian',
      },
      {
        count: 0,
        description:
          'Delicate, precise, and deeply satisfying Japanese cooking.',
        filters: { cuisine: 'japanese' },
        id: 'japanese',
        image: '',
        label: 'Japanese',
      },
      {
        count: 0,
        description:
          'Bright, bold Mexican flavours — chilli, lime, and plenty of spice.',
        filters: { cuisine: 'mexican' },
        id: 'mexican',
        image: '',
        label: 'Mexican',
      },
      {
        count: 2,
        description: 'Fragrant tagines and North African spice.',
        filters: { cuisine: 'moroccan' },
        id: 'moroccan',
        image: '/images/recipes/lamb-tagine.jpg',
        label: 'Moroccan',
      },
      {
        count: 0,
        description:
          'Tapas, paella, and the bold flavours of the Iberian peninsula.',
        filters: { cuisine: 'spanish' },
        id: 'spanish',
        image: '',
        label: 'Spanish',
      },
      {
        count: 0,
        description:
          'Fragrant, fresh, and balanced — the hallmarks of Thai cooking.',
        filters: { cuisine: 'thai' },
        id: 'thai',
        image: '',
        label: 'Thai',
      },
      {
        count: 0,
        description:
          'Rich spices, slow braises, and the warmth of Turkish hospitality.',
        filters: { cuisine: 'turkish' },
        id: 'turkish',
        image: '',
        label: 'Turkish',
      },
    ],
    order: 5,
    showInMenu: true,
    title: 'By Cuisine',
  },
  {
    id: 'proteins',
    items: [
      {
        count: 1,
        description: 'From quick steak to slow-braised — bold beef recipes.',
        filters: { proteins: 'beef' },
        id: 'beef',
        image: '/images/recipes/steak-rarebit.webp',
        label: 'Beef',
      },
      {
        count: 1,
        description: 'Endlessly versatile — eggs at the heart of the dish.',
        filters: { proteins: 'eggs' },
        id: 'eggs',
        image: '/images/recipes/ham-and-cheese-galettes.webp',
        label: 'Eggs',
      },
      {
        count: 1,
        description: 'Fresh and simple fish recipes for any night.',
        filters: { proteins: 'fish' },
        id: 'fish',
        image: '/images/recipes/cod-with-roasted-chilli-butter.webp',
        label: 'Fish',
      },
      {
        count: 1,
        description: 'Rich, flavourful lamb from quick chops to slow shoulder.',
        filters: { proteins: 'lamb' },
        id: 'lamb',
        image: '/images/recipes/lamb-tagine.jpg',
        label: 'Lamb',
      },
      {
        count: 3,
        description: 'Hearty pulses — lentils, chickpeas, and beans.',
        filters: { proteins: 'legumes' },
        id: 'legumes',
        image: '/images/recipes/curried-lentil-cottage-pie.webp',
        label: 'Legumes',
      },
      {
        count: 0,
        description: 'Belly, chops, sausages, and beyond — pork at its best.',
        filters: { proteins: 'pork' },
        id: 'pork',
        image: '',
        label: 'Pork',
      },
      {
        count: 4,
        description:
          'The weeknight staple — quick, easy, and always satisfying.',
        filters: { proteins: 'chicken' },
        id: 'chicken',
        image: '/images/recipes/chilli-chicken.webp',
        label: 'Chicken',
      },
      {
        count: 0,
        description:
          'Leaner than chicken, just as versatile — turkey beyond Christmas.',
        filters: { proteins: 'turkey' },
        id: 'turkey',
        image: '',
        label: 'Turkey',
      },
      {
        count: 3,
        description: 'Prawns, clams, and the best of the sea.',
        filters: { proteins: 'seafood' },
        id: 'seafood',
        image: '/images/recipes/clam-prawn-chorizo-linguine.webp',
        label: 'Seafood',
      },
    ],
    order: 6,
    showInMenu: true,
    title: 'By Ingredient',
  },
  {
    id: 'special_occasions',
    items: [
      {
        count: 0,
        description:
          'Crowd-pleasing recipes built for the grill and the garden.',
        filters: { special_occasions: 'bbq' },
        id: 'bbq',
        image: '',
        label: 'BBQ',
      },
      {
        count: 0,
        description: 'Festive recipes for the most indulgent time of year.',
        filters: { special_occasions: 'christmas' },
        id: 'christmas',
        image: '',
        label: 'Christmas',
      },
      {
        count: 0,
        description: 'All the trimmings — the full Sunday roast spread.',
        filters: { special_occasions: 'sunday-roast' },
        id: 'sunday-roast',
        image: '',
        label: 'Sunday Roast',
      },
    ],
    order: 7,
    showInMenu: true,
    title: 'By Occasion',
  },
  {
    id: 'dietary_restrictions',
    items: [
      {
        count: 1,
        description: 'Great cooking that happens to be gluten free.',
        filters: { dietary_restrictions: 'gluten-free' },
        id: 'gluten-free',
        image: '/images/recipes/ham-and-cheese-galettes.webp',
        label: 'Gluten Free',
      },
      {
        count: 0,
        description:
          'Fish and seafood, no meat — flavourful pescatarian cooking.',
        filters: { dietary_restrictions: 'pescatarian' },
        id: 'pescatarian',
        image: '',
        label: 'Pescatarian',
      },
      {
        count: 3,
        description: 'Meat-free recipes that are anything but boring.',
        filters: { dietary_restrictions: 'vegetarian' },
        id: 'vegetarian',
        image: '/images/recipes/curried-lentil-cottage-pie.webp',
        label: 'Vegetarian',
      },
    ],
    order: 8,
    showInMenu: true,
    title: 'By Diet',
  },
];
